"""Custom DSPy Language Model for Databricks Supervisor Agent.

Properly subclasses ``dspy.BaseLM`` and overrides ``forward()`` so that
DSPy's built-in caching, callbacks, and history tracking all function
correctly.  Sets ``model_type="responses"`` so the base class routes
output extraction through ``_process_response()``.

DSPy best-practice notes
~~~~~~~~~~~~~~~~~~~~~~~~
* The previous implementation subclassed ``dspy.clients.lm.LM`` and
  overrode ``__call__``, which silently bypassed the ``@with_callbacks``
  decorator, history tracking, and cache integration.
* ``dspy.BaseLM`` is the documented extension point (DSPy 3.x).
  Subclasses override **only** ``forward()`` and return a raw
  OpenAI-compatible response object.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import Any

import dspy


class DatabricksResponsesLM(dspy.BaseLM):
    """DSPy LM adapter for Databricks Responses API endpoints.

    The Supervisor Agent (MAS) created in Lab 6 exposes an
    endpoint that speaks the OpenAI *Responses* API format
    (``input`` array, not ``messages``).

    Authentication is handled by the Databricks SDK WorkspaceClient:

    * **On Databricks clusters** — automatic runtime credentials.
    * **Locally** — ``DATABRICKS_HOST`` and ``DATABRICKS_TOKEN``
      environment variables.
    """

    def __init__(self, model: str, **kwargs: Any) -> None:
        # ``model_type="responses"`` tells ``BaseLM._process_lm_response``
        # to use ``_process_response()`` which understands the Responses
        # API output shape.
        super().__init__(model=model, model_type="responses", **kwargs)
        self._client: Any = None

    # -- internal helpers --------------------------------------------------

    def _get_client(self) -> Any:
        """Lazily create the Databricks OpenAI-compatible client."""
        if self._client is not None:
            return self._client

        from databricks.sdk import WorkspaceClient

        wc = WorkspaceClient()
        self._client = wc.serving_endpoints.get_open_ai_client()
        return self._client

    # -- BaseLM contract ---------------------------------------------------

    def forward(
        self,
        prompt: str | None = None,
        messages: list[dict[str, Any]] | None = None,
        **kwargs: Any,
    ) -> Any:
        """Call the MAS endpoint and return the raw OpenAI response object.

        ``BaseLM.__call__`` (decorated with ``@with_callbacks``) invokes
        this method, then routes the return value through
        ``_process_lm_response`` for history / caching / output
        extraction.

        MAS endpoints only support single-turn conversations, so we
        combine multi-turn messages (generated by DSPy's default
        ``ChatAdapter``) into one user message before sending.
        """
        client = self._get_client()

        if messages:
            parts: list[str] = []
            for msg in messages:
                role = msg.get("role", "user")
                content = msg.get("content", "")
                if role in ("system", "user"):
                    parts.append(content)
                elif role == "assistant":
                    parts.append(f"Assistant: {content}")
            input_messages = [{"role": "user", "content": "\n\n".join(parts)}]
        elif prompt:
            input_messages = [{"role": "user", "content": prompt}]
        else:
            raise ValueError("Either prompt or messages must be provided")

        response = client.responses.create(
            model=self.model,
            input=input_messages,
        )

        # MAS endpoints may not return token counts.
        # ``BaseLM._process_lm_response`` calls ``dict(response.usage)``,
        # so we must ensure the attribute is present.
        if not hasattr(response, "usage") or response.usage is None:
            response.usage = SimpleNamespace(
                prompt_tokens=0,
                completion_tokens=0,
                total_tokens=0,
            )

        return response


def configure_dspy(
    model_name: str,
    *,
    temperature: float = 0.1,
    max_tokens: int = 4000,
) -> DatabricksResponsesLM:
    """One-call DSPy setup for Databricks MAS endpoints.

    Creates the LM and calls ``dspy.configure``.  ``ChatAdapter`` is the
    default adapter in DSPy 3.x and does not need to be set explicitly.

    Returns the configured LM so callers can inspect ``lm.history``.
    """
    lm = DatabricksResponsesLM(
        model=model_name,
        temperature=temperature,
        max_tokens=max_tokens,
    )

    # ChatAdapter is the default — no need to pass adapter=.
    dspy.configure(lm=lm, track_usage=True)

    print(f"[OK] DSPy configured  endpoint={model_name}  "
          f"temp={temperature}  max_tokens={max_tokens}")
    return lm
